CC = gcc
CFLAGS = -Wall
TARGET = TimeSync

all: $(TARGET)

$(TARGET): $(TARGET).o
    $(CC) $(CFLAGS) -o $(TARGET) $(TARGET).o

$(TARGET).o: $(TARGET).c
    $(CC) $(CFLAGS) -c $(TARGET).c

clean:
    rm -f $(TARGET) $(TARGET).o
